import { useEffect } from 'react';
import useAppStore from '../stores/appStore';
import usePipeline from '../hooks/usePipeline';
import { getReport } from '../utils/api';
import Chat from '../components/Chat';
import CaseForm from '../components/CaseForm';
import PipelineTracker from '../components/PipelineTracker';
import ReportViewer from '../components/ReportViewer';

export default function HomePage() {
  const { activeCase, pipelineStatus, report, setReport, addMessage } =
    useAppStore();

  // Connect to pipeline WebSocket when a case is active
  usePipeline(activeCase?.id);

  // Fetch report when pipeline completes
  useEffect(() => {
    if (pipelineStatus === 'complete' && activeCase?.id && !report) {
      getReport(activeCase.id)
        .then((r) => {
          setReport(r);
          addMessage({
            role: 'ai',
            content: 'Report is ready. You can view the full analysis below or ask follow-up questions.',
            ts: new Date().toISOString(),
          });
        })
        .catch((err) => {
          addMessage({
            role: 'ai',
            content: `Failed to load report: ${err.message}`,
            ts: new Date().toISOString(),
            error: true,
          });
        });
    }
  }, [pipelineStatus, activeCase, report, setReport, addMessage]);

  return (
    <div className="h-screen flex flex-col">
      {/* Chat area + sidebar */}
      <div className="flex flex-1 min-h-0">
        {/* Left: Chat */}
        <div className="flex-1 flex flex-col min-w-0">
          <Chat />
        </div>

        {/* Right: Pipeline tracker (when running) */}
        {activeCase && pipelineStatus !== 'complete' && (
          <aside className="w-80 border-l bg-gray-50 p-4 overflow-y-auto">
            <PipelineTracker />
          </aside>
        )}
      </div>

      {/* Report viewer (when available) */}
      {report && (
        <div className="border-t bg-white p-6 max-h-[60vh] overflow-y-auto">
          <ReportViewer report={report} caseId={activeCase?.id} />
        </div>
      )}

      {/* Case form modal */}
      <CaseForm />

      {/* Disclaimer */}
      <footer className="bg-gray-50 border-t px-6 py-4">
        <div className="max-w-4xl mx-auto space-y-3 text-[11px] leading-relaxed text-gray-500">
          <p className="font-semibold text-gray-600 uppercase tracking-wide text-[10px]">
            Critical Disclaimer
          </p>
          <p>
            This report is generated by an AI Agentic Workflow (MedGemma 1.5 + STORM).
            It is intended for informational and research purposes only and constitutes
            a &ldquo;Clinical Second Opinion&rdquo; based on available digital records.
            It is <span className="font-medium text-gray-600">not</span> a confirmatory
            clinical diagnosis. The findings presented here represent probabilistic
            hypotheses based on medical literature and should be reviewed by a licensed
            specialist before any treatment change.
          </p>
          <p className="font-medium text-gray-600">
            No Emergency Use: Do not use this portal for medical emergencies. If you are
            in critical distress, contact your local emergency services immediately.
          </p>
          <div className="border-t border-gray-200 pt-2 mt-2 space-y-1">
            <p>
              <span className="font-medium text-gray-600">Standard Output</span>
              {' '}&mdash; &ldquo;Evidence-Backed Verification&rdquo;: An independent
              review of existing clinical data to calculate the statistical probability
              of the referring diagnosis versus common alternatives.
            </p>
            <p>
              <span className="font-medium text-gray-600">Think Zebra (Beta Mode)</span>
              {' '}&mdash; &ldquo;Differential Discovery (Experimental)&rdquo;: A
              specialized search for low-prevalence conditions and anomalies. These are
              hypothetical differentials intended to guide specialist investigation and do
              not confirm a rare disease and are not clinical recommendations.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
