import { useEffect, useState } from 'react';
import useAppStore from '../stores/appStore';
import useToastStore from '../stores/toastStore';
import usePipeline from '../hooks/usePipeline';
import { getReport } from '../utils/api';
import Chat from '../components/Chat';
import CaseForm from '../components/CaseForm';
import PipelineTracker from '../components/PipelineTracker';
import ReportViewer from '../components/ReportViewer';

export default function HomePage() {
  const { activeCase, pipelineStatus, report, setReport, addMessage } =
    useAppStore();
  const addToast = useToastStore((s) => s.addToast);

  // Connect to pipeline WebSocket when a case is active
  usePipeline(activeCase?.id);

  // Fetch report when pipeline completes
  useEffect(() => {
    if (pipelineStatus === 'complete' && activeCase?.id && !report) {
      getReport(activeCase.id)
        .then((r) => {
          setReport(r);
          addToast('Your report is ready', 'success');
          addMessage({
            role: 'ai',
            content: 'Report is ready. You can view the full analysis below or ask follow-up questions.',
            ts: new Date().toISOString(),
          });
        })
        .catch((err) => {
          addMessage({
            role: 'ai',
            content: `Failed to load report: ${err.message}`,
            ts: new Date().toISOString(),
            error: true,
          });
        });
    }
  }, [pipelineStatus, activeCase, report, setReport, addMessage]);

  return (
    <div className="h-screen flex flex-col">
      {/* Chat area + sidebar */}
      <div className="flex flex-1 min-h-0">
        {/* Left: Chat */}
        <div className="flex-1 flex flex-col min-w-0">
          <Chat />
        </div>

        {/* Right: Pipeline tracker (when running) */}
        {activeCase && pipelineStatus !== 'complete' && (
          <aside className="w-80 border-l bg-gray-50 p-4 overflow-y-auto">
            <PipelineTracker />
          </aside>
        )}
      </div>

      {/* Report viewer (when available) */}
      {report && (
        <div className="border-t bg-white p-6 max-h-[60vh] overflow-y-auto">
          <ReportViewer report={report} caseId={activeCase?.id} />
        </div>
      )}

      {/* Case form modal */}
      <CaseForm />

      {/* Disclaimer — collapsible */}
      <Disclaimer />
    </div>
  );
}

function Disclaimer() {
  const [open, setOpen] = useState(false);

  return (
    <footer className="bg-gray-50 border-t px-6 py-2 shrink-0">
      <button
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center justify-between text-[10px] font-semibold text-gray-500 uppercase tracking-wide hover:text-gray-700 transition-colors"
      >
        <span>Critical Disclaimer &mdash; AI-generated, not a clinical diagnosis</span>
        <span className="text-xs">{open ? '\u25B2' : '\u25BC'}</span>
      </button>
      {open && (
        <div className="max-w-4xl mx-auto mt-2 space-y-2 text-[11px] leading-relaxed text-gray-500">
          <p>
            This report is generated by the SECND Reporter Engine.
            It is intended for informational and research purposes only and constitutes
            a &ldquo;Clinical Second Opinion&rdquo; based on available digital records.
            It is <span className="font-medium text-gray-600">not</span> a confirmatory
            clinical diagnosis.
          </p>
          <p className="font-medium text-gray-600">
            No Emergency Use: Do not use this portal for medical emergencies.
          </p>
          <div className="border-t border-gray-200 pt-2 mt-1 space-y-1">
            <p>
              <span className="font-medium text-gray-600">Standard Output</span>
              {' '}&mdash; Evidence-Backed Verification of the referring diagnosis.
            </p>
            <p>
              <span className="font-medium text-gray-600">Think Zebra (Beta)</span>
              {' '}&mdash; Differential Discovery for low-prevalence conditions. Not clinical recommendations.
            </p>
          </div>
        </div>
      )}
    </footer>
  );
}
